import type { Metadata } from "next";
import "./globals.css";
import ClientProviders from "./providers/client-provider";
import { AuthGuard } from "@/ processes/auth/AuthGuard";
import StoreProvider from "./providers/store-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <ClientProviders>
            <AuthGuard>
              {children}
            </AuthGuard>
            <br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
          </ClientProviders>
        </StoreProvider>
      </body>
    </html>
  );
}

